server:
  port: 8080


elasticsearch:
  schema: http
  servers: 192.168.10.71:9200
  connectTimeout: 5000
  socketTimeout: 3000
  connectRequestTimeout: 5000
  maxConnectNum: 100
  maxConnectPerRoute: 100

