server:
  port: 8080


elasticsearch:
  schema: http
  servers: 10.1.10.222:9200
  connectTimeout: 5000
  socketTimeout: 3000
  connectRequestTimeout: 5000
  maxConnectNum: 100
  maxConnectPerRoute: 100

