server:
  port: 8060

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_test1?serverTimezone=CST
    password: 123.com
    username: root

mybatis:
  mapper-locations: classpath*:/mybatis/mapper/*.xml
  type-aliases-package: com.chige.domain
