#FROM spring-boot-docker:1.0
## Adding build tools to make yarn install work on Apple silicon / arm64 machines
#RUN apk add --no-cache python2 g++ make
#WORKDIR /app
#COPY . .
#RUN yarn install --production
#CMD ["node", "src/index.js"]