server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot_test1?serverTimezone=CST
    username: root
    password: 123.com

  jpa:
    # \u81EA\u52A8\u521B\u5EFA\uFF0C\u66F4\u65B0\uFF0C\u9A8C\u8BC1\u6570\u636E\u5E93\u8868\u7ED3\u6784
    hibernate:
      ddl-auto: update
      #\u8BBE\u7F6E\u6570\u636E\u5E93\u5F15\u64CE\u4E3AInnodb
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # \u6253\u5370SQL\u8BED\u53E5\uFF0C\u65B9\u4FBF\u8C03\u8BD5
    show-sql: true

